### ISSUE TITLE
Fatal error when installing plugin

### ISSUE THREAD

**Issue by nickdanks** [WeFoster/bp-feeds#65]
Fatal error: Call to undefined function get_current_screen() in /homepages/12/d271869397/htdocs/clickandbuilds/Community/wp-content/plugins/bp-feeds-develop/core/admin.php on line 388

**Comment by slaFFik** [comment]
Wow.
How is your WordPress installed? WPMS or ordinary WP? Where and how BuddyPress is installed?

**Comment by nickdanks** [comment]
Its installed through our hosting and buddy press is installed as a plugin.
http://community.distinctivegroup.co.uk/

**Comment by nickdanks** [comment]
Ive had to take it down now as it broke the site with a white screen.

**Comment by slaFFik** [comment]
No, I'm asking - do you have [WordPress MultiSite](http://codex.wordpress.org/Create_A_Network). If yes - BuddyPress is activated Network wide or on a specific site of your network?

**Comment by nickdanks** [comment]
Ok, its on a specific site to our domain.

**Comment by slaFFik** [comment]
Please confirm:

1. you have WordPress MultiSite with several sites inside your network.
2. BuddyPress and BP Fees plugins are both activated on a specific site inside a network (**not** network-wide)

**Comment by nickdanks** [comment]
Please confirm:

1. you have WordPress MultiSite with several sites inside your network. - No this is just one website associated with the domain and not a multisite 
2. BuddyPress and BP Fees plugins are both activated on a specific site inside a network (not network-wide) - Buddy Press is installed but im not sure what BP Fees is as i dont have this installed.

**Comment by slaFFik** [comment]
BP Feeds is the plugin you are writing in repository in. Scroll to the top of the page.

**Comment by nickdanks** [comment]
ok no that is not installed as i get the fatel error and it breaks the website.

**Comment by nickdanks** [comment]
Any thoughts? Thanks

**Comment by slaFFik** [comment]
No thoughts currently. I will test the plugin today in the evening and will try to reproduce/fix if possible.

**Comment by nickdanks** [comment]
ok thank you very much.

**Comment by hughankers** [comment]
Hi, I've been trying out this plugin on a trial version of a Wordpress/Buddypress site I'm developing and it worked perfectly well at first then after a short while I had reason to click the "Customise" link on my site's admin bar and got the following fatal error message:

Fatal error: Call to undefined function get_current_screen() in /home/example1234/public_html/wp-content/plugins/bp-feeds-develop/core/admin.php on line 388

(where "example1234" represents my real home directory name)
I was able to recover by going back one page on my browser, then I was able to navigate normally to the "installed plugins" page and de-activate the plugin. 

My site is a single install of Wordpress 4.4.2. I really like this plugin and if you can get it to work reliably I'll definitely install it on the production version of my site, but in the meantime, I'd be happy to test it on my trial site and report any errors or unexpected behaviour.

**Comment by hughankers** [comment]
Hi slaFFik, I have a little further information about this fatal error. 

I decided to re-install the plugin for further testing and it seems to work quite normally except when attempting to access the theme customization editor. Every other method of navigating my site seems perfectly OK, including logging in and out, navigating through all the admin dashboard links and other plugin settings, navigating between various pages on the site's front end via menu links etc etc.

It would seem like it's **_only_** when I try to access the customizer that the error occurs.
You probably already know this, but I've only just realised that the "Customize" link on the adminbar, is not a static (fixed) url. Wordpress automatically appends the url of the current screen to the end of the Customize page's url... Obviously in order to return you to the page you came from before using the Customizer.

For example on my site media.lioar.com. If I'm currently on my own user profile page and hover my mouse over the Customize link, the target url looks like this...

http://media.lioar.com/wp-admin/customize.php?url=http%3A%2F%2Fmedia.lioar.com%2Fmembers%2Flioar%2F

I don't know enough about how Wordpress generates dynamic urls like that to hazard a guess if that's causing the error, but it does seem like it may have something to do with it.

**Comment by hughankers** [comment]
Just to add to my last comment. I tried clicking that customize link to test it after publishing the comment and of course I got exactly the same fatal error message as before. I also tried clicking it after logging out of my site and this time it just redirects to the /wp-login page where I was able to log in successfully using my GitHub account. 

If it would help you to have admin access to my site, to recreate the error yourself and see how my site is configured eg which other plugins are installed etc. I'd be happy to let you do that. My site is just a test version, with no other registered users and I have recent backups, so no big deal if it breaks.

If you want to do that, just click the link in my previous comment to take you to the login page and then click the GitHub icon to login. As soon as I see that you've joined, I'll upgrade your account to Administrator status so you can poke around in the admin area etc.

**Comment by slaFFik** [comment]
Found the problem. Will update the repo today.
